package cn.com.webxml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2018-02-01T21:23:22.059+08:00
 * Generated source version: 3.1.14
 * 
 */
@WebService(targetNamespace = "http://WebXml.com.cn/", name = "ChinaOpenFundWSSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ChinaOpenFundWSSoap {

    /**
     * 
     *             
     */
    @WebResult(name = "getOpenFundDataSetByCodeResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getOpenFundDataSetByCode", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetOpenFundDataSetByCode")
    @WebMethod(action = "http://WebXml.com.cn/getOpenFundDataSetByCode")
    @ResponseWrapper(localName = "getOpenFundDataSetByCodeResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetOpenFundDataSetByCodeResponse")
    public cn.com.webxml.GetOpenFundDataSetByCodeResponse.GetOpenFundDataSetByCodeResult getOpenFundDataSetByCode(
            @WebParam(name = "userID", targetNamespace = "http://WebXml.com.cn/")
                    String userID,
            @WebParam(name = "FundCode", targetNamespace = "http://WebXml.com.cn/")
                    String fundCode
    );

    /**
     * 
     *             
     */
    @WebResult(name = "getFundCodeNameStringResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getFundCodeNameString", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetFundCodeNameString")
    @WebMethod(action = "http://WebXml.com.cn/getFundCodeNameString")
    @ResponseWrapper(localName = "getFundCodeNameStringResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetFundCodeNameStringResponse")
    public cn.com.webxml.ArrayOfString getFundCodeNameString();

    /**
     * 
     *             
     */
    @WebResult(name = "getOpenFundDataSetResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getOpenFundDataSet", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetOpenFundDataSet")
    @WebMethod(action = "http://WebXml.com.cn/getOpenFundDataSet")
    @ResponseWrapper(localName = "getOpenFundDataSetResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetOpenFundDataSetResponse")
    public cn.com.webxml.GetOpenFundDataSetResponse.GetOpenFundDataSetResult getOpenFundDataSet(
            @WebParam(name = "userID", targetNamespace = "http://WebXml.com.cn/")
                    String userID
    );

    /**
     * 
     *             
     */
    @WebResult(name = "getFundCodeNameDataSetResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getFundCodeNameDataSet", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetFundCodeNameDataSet")
    @WebMethod(action = "http://WebXml.com.cn/getFundCodeNameDataSet")
    @ResponseWrapper(localName = "getFundCodeNameDataSetResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetFundCodeNameDataSetResponse")
    public cn.com.webxml.GetFundCodeNameDataSetResponse.GetFundCodeNameDataSetResult getFundCodeNameDataSet();

    /**
     * 
     *             
     */
    @WebResult(name = "getOpenFundStringByCodeResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getOpenFundStringByCode", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetOpenFundStringByCode")
    @WebMethod(action = "http://WebXml.com.cn/getOpenFundStringByCode")
    @ResponseWrapper(localName = "getOpenFundStringByCodeResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetOpenFundStringByCodeResponse")
    public cn.com.webxml.ArrayOfString getOpenFundStringByCode(
            @WebParam(name = "userID", targetNamespace = "http://WebXml.com.cn/")
                    String userID,
            @WebParam(name = "FundCode", targetNamespace = "http://WebXml.com.cn/")
                    String fundCode
    );

    /**
     * 
     *             
     */
    @WebResult(name = "getOpenFundStringResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getOpenFundString", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetOpenFundString")
    @WebMethod(action = "http://WebXml.com.cn/getOpenFundString")
    @ResponseWrapper(localName = "getOpenFundStringResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetOpenFundStringResponse")
    public cn.com.webxml.ArrayOfString getOpenFundString(
            @WebParam(name = "userID", targetNamespace = "http://WebXml.com.cn/")
                    String userID
    );
}
