package cn.com.webxml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2018-02-01T21:23:22.047+08:00
 * Generated source version: 3.1.14
 * 
 */
@WebService(targetNamespace = "http://WebXml.com.cn/", name = "ChinaOpenFundWSHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ChinaOpenFundWSHttpPost {

    /**
     * 
     *             
     */
    @WebResult(name = "DataSet", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod
    public DataSet getOpenFundDataSetByCode(
            @WebParam(partName = "userID", name = "userID", targetNamespace = "http://WebXml.com.cn/")
                    String userID,
            @WebParam(partName = "FundCode", name = "FundCode", targetNamespace = "http://WebXml.com.cn/")
                    String fundCode
    );

    /**
     * 
     *             
     */
    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod
    public ArrayOfString getFundCodeNameString();

    /**
     * 
     *             
     */
    @WebResult(name = "DataSet", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod
    public DataSet getOpenFundDataSet(
            @WebParam(partName = "userID", name = "userID", targetNamespace = "http://WebXml.com.cn/")
                    String userID
    );

    /**
     * 
     *             
     */
    @WebResult(name = "DataSet", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod
    public DataSet getFundCodeNameDataSet();

    /**
     * 
     *             
     */
    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod
    public ArrayOfString getOpenFundStringByCode(
            @WebParam(partName = "userID", name = "userID", targetNamespace = "http://WebXml.com.cn/")
                    String userID,
            @WebParam(partName = "FundCode", name = "FundCode", targetNamespace = "http://WebXml.com.cn/")
                    String fundCode
    );

    /**
     * 
     *             
     */
    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod
    public ArrayOfString getOpenFundString(
            @WebParam(partName = "userID", name = "userID", targetNamespace = "http://WebXml.com.cn/")
                    String userID
    );
}
